version: '3.1'

services:
  gitpress:
    build: ../.
    ports:
      - 80:80
      - 443:443
    environment:
      GITPRESS_MODE: FETCH
      WORDPRESS_URL: http://localhost/
      GIT_ORIGIN: github.com/pschoffer/gitpress-example.git
